AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role and Policy needed for step function

Parameters:
  EnvType:
    Description: "Environment type"
    Default: dev
    Type: String
    AllowedValues: [dev, test, prod]
    ConstraintDescription: must specify prod, dev, or test.


Resources:
  SfnRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 'states.amazonaws.com'
            Action: 'sts:AssumeRole'
      RoleName: !Sub 'sample-${EnvType}-role'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/lz/power-user'

  LambdaTriggPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: This Policy is used to access services needed by step function 
      ManagedPolicyName: !Sub 'sample-${EnvType}-policy'
      Roles:
        - Ref: SfnRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "ExecutStepFunctionAccess"
            Effect: Allow
            Action:
                - 'states:StartExecution'
            Resource:
              - !Sub 'arn:aws:states:us-east-1:${AWS::AccountId}:execution:sample-${EnvType}-*:*'

          - Sid: "GlueJobExecutionAccess"
            Effect: Allow
            Action:
              - glue:StartJobRun
              - glue:GetJobs
              - glue:GetJobRun
              - glue:ListJobs
              - glue:GetJobRuns
              - glue:GetJob
            Resource:
              -  !Sub 'arn:aws:glue:us-east-1:${AWS::AccountId}:job/sample-${EnvType}-*'

          - Sid: "CloudWatchEventsAccess"
            Effect: Allow
            Action:
              - events:PutTargets
              - events:PutRule
              - events:DescribeRule
            Resource:
              - !Sub 'arn:aws:events:us-east-1:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule'

          - Sid: "AllowKMSAccess"
            Effect: Allow
            Action:
                - 'kms:DescribeKey'
                - 'kms:GenerateDataKey'
                - 'kms:Decrypt'
                - 'kms:Encrypt'
            Resource:
              - !Join
                - ''
                - - !Sub 'arn:aws:kms:us-east-1:${AWS::AccountId}:key/'
                  - Fn::ImportValue:
                      !Sub "sample-${EnvType}-kms-sns-id"


          - Sid: "SNSAccessPublish"
            Effect: Allow
            Action:
              - sns:Publish
            Resource:
              - !Sub 'arn:aws:sns:us-east-1:${AWS::AccountId}:sample-${EnvType}-*'